name: auth
description: Auth Service
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  conduit: ^5.1.3
  conduit_core: ^5.1.3
  conduit_postgresql: ^5.1.3
  jaguar_jwt: 3.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
